name: Python Test & Build

on:
  push:
    branches: [ "main" ]  # Rulează la push pe main
  pull_request:
    branches: [ "main" ]  # Rulează la PR către main

jobs:
  test:
    runs-on: ubuntu-latest  # Mediu de execuție

    steps:
      # 1. Checkout codul
      - uses: actions/checkout@v4

      # 2. Configurează Python
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"  # Sau versiunea ta

      # 3. Instalează dependințe
      - name: Instalare dependințe
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Rulează testele cu pytest
      - name: Testare automată
        run: pytest test_main.py -v

      # 5. (Opțional) Verifică build-ul
      - name: Verificare build
        run: python main.py  # Execută codul principal